/XrayTube/phys/addPhysics  emstandard_opt4

/process/em/deexcitationIgnoreCut true
/process/em/fluo true
/run/setCut 10 um
/process/em/setBiasingFactor eBrem 1000 true
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
# /run/numberOfThreads 2
#
# Initialize kernel
/run/initialize
#
#
/control/execute macros/vis.mac
